apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vaultwarden
  name: vaultwarden
spec:
  ports:
  - name: http
    port: 8090
    protocol: TCP
    targetPort: 80
  selector:
    app: vaultwarden
  type: ClusterIP
status:
  loadBalancer: {}
