apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vaultwarden
  name: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vaultwarden
    spec:
      containers:
      - image: vaultwarden/server:latest
        name: server
        resources: {}
status: {}
