apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsGroup: 999
      containers:
        - image: postgres:17.5-bookworm
          name: postgres
          envFrom:
            - secretRef: 
                name: postgres
          securityContext:
            allowPrivilegeEscalation: false
          resources: {}
          ports:
            - containerPort: 5432
