apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # Optional: force redirect https
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: pgadmin.heroaero.dev
      http:
        paths:
          - backend:
              service:
                name: pgadmin
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - pgadmin.heroaero.dev
      secretName: pgadmin-tls
