apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata: 
  name: reloader
  namespace: reloader
spec:
  interval: 10m 
  chart:
    spec:
      chart: reloader
      version: "v1.0.59"
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
  values:
    reloader:
      auto: true
