apiVersion: apps/v1
kind: Deployment 
metadata:
  name: pgadmin-deployment 
  namespace: test-dev 
  labels:
    tier: admin
    app: admin
    env: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      env: pgadmin
  template:
    metadata:
      name: pgadmin-pod 
      labels:
        env: pgadmin
    spec:
      serviceAccountName: app-sa
      nodeName: toaster
      containers:
        - name: pgadmin 
          image: dpage/pgadmin4:9.4 
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret 
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: PGADMIN_DEFAULT_PASSWORD
          ports:
            - containerPort: 80
