apiVersion: apps/v1
kind: Deployment 
metadata:
  name: cloudflared
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      securityContext:
        sysctls:
        # allow ICMP traffic (ping, traceroute) to resources behind cloudflared
          - name: net.ipv4.ping_group_range
            value: "65532 65532"
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          envFrom:
            - secretRef:
                name: cloudflared-secret 
          command:
            # configures tunnel run paramaters
            - cloudflared
            - tunnel
            - --no-autoupdate
            - --loglevel
            - debug
            - --metrics
            - 0.0.0.0:2000
            - --config 
            - /etc/cloudflared/config/config.yaml
            - run
          livenessProbe:
            httpGet: 
              # cloudflared has a /ready endpoint which returns 200 if and only if
              # it has a connection to cloudflare's network.
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true 
      volumes:
        - name: config
          configMap:
            name: cloudflared-config
--- 
apiVersion: v1
kind: ConfigMap 
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    ingress:
      - hostname: link.heroaero.net
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: heroaero.dev 
        service: http://homepage-svc.test-dev.svc.cluster.local
      - hostname: ranch.heroaero.net
        service: https://traefik.kube-system.svc.cluster.local:443
      - hostname: pgadmin.heroaero.net
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: graf.heroaero.info
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: longhorn.heroaero.net
        service: http://longhorn-frontend.longhorn-system.svc.cluster.local
      - service: http_status:404
