apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m 
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "75.6.1"
      # version: "58.x"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring
      interval: 12h 
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is interested during install
      - paths: ["/metadata/annotation/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
  values:
    grafana:
      adminPassword: aero
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - graf.heroaero.info
        ## Secret must be manually created in the namespace
        ##
        tls:
         - secretName: grafana-tls-secret
           hosts:
           - graf.heroaero.info
