apiVersion: external-secrets.io/v1
kind: ExternalSecret 
metadata:
  name: cloudflared-eso
  namespace: cloudflared   
spec:
  refreshInterval: 1m 
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore 
  target:
    name: cloudflared-secret 
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: cloudflare-secret 
